"""
Streamlit dashboard for real-time monitoring of fraud detection.

WHY:
Machine Learning models in production are not 'fire and forget'. Data distributions
shift, models degrade, and business stakeholders need visibility into what the system
is doing. A real-time dashboard provides immediate feedback on system performance.

MENTOR NOTE (ML Dashboards):
An effective ML dashboard shows 3 things:
1. Operational metrics (latency, throughput)
2. Model metrics (predictions, probabilities, drift)
3. Business metrics (fraud rate, estimated dollar value saved/lost)

Usage:
    streamlit run scripts/run_dashboard.py
"""

import sys
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

import pandas as pd
import streamlit as st
import matplotlib

# Select a headless backend before importing pyplot. This is required by
# environments such as Streamlit Community Cloud, which have no display server.
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from src.config import LOGS_DIR

st.set_page_config(
    page_title="Fraud Detection Dashboard",
    page_icon="🛡️",
    layout="wide"
)


def load_prediction_logs():
    """Load prediction logs generated by the API."""
    log_file = Path(LOGS_DIR) / "prediction_logs.csv"

    if not log_file.exists():
        return pd.DataFrame()

    try:
        df = pd.read_csv(log_file)
        if 'timestamp' in df.columns:
            df['timestamp'] = pd.to_datetime(df['timestamp'])
        return df
    except Exception as e:
        st.error(f"Error loading logs: {e}")
        return pd.DataFrame()


# ============================================================
# DASHBOARD LAYOUT
# ============================================================
st.title("🛡️ Credit Card Fraud Detection — Live Dashboard")

# --- Sidebar ---
with st.sidebar:
    st.header("⚙️ Settings")
    threshold = st.slider("Alert Threshold", 0.0, 1.0, 0.5, 0.05)

    if st.button("🔄 Refresh Data", type="primary"):
        st.rerun()

    st.markdown("---")
    st.info(
        "**MENTOR NOTE:** In a real system, changing the threshold here "
        "might update a distributed config (like Redis) which the FastAPI "
        "instances listen to, dynamically altering the decision boundary."
    )

# --- Main Content ---
df = load_prediction_logs()

if df.empty:
    st.warning(
        "📭 No prediction logs found yet.\n\n"
        "**To see data here:**\n"
        "1. Run the API: `uvicorn api.app:app --reload`\n"
        "2. Run the simulator: `python scripts/simulate_stream.py`\n"
        "3. Come back and click Refresh!"
    )
else:
    # Re-evaluate frauds based on the interactive threshold
    df['is_flagged'] = df['probability'] >= threshold

    # --- Key Metrics Cards ---
    col1, col2, col3, col4 = st.columns(4)
    total_tx = len(df)
    total_frauds = int(df['is_flagged'].sum())
    fraud_rate = (total_frauds / total_tx) * 100 if total_tx > 0 else 0

    col1.metric("Total Transactions", f"{total_tx:,}")
    col2.metric("Frauds Flagged", f"{total_frauds:,}")
    col3.metric("Fraud Rate", f"{fraud_rate:.2f}%")
    col4.metric("Avg Threshold", f"{threshold:.2f}")

    st.markdown("---")

    # --- Charts ---
    col_chart1, col_chart2 = st.columns(2)

    with col_chart1:
        st.subheader("📈 Fraud Probability Over Time")
        fig1, ax1 = plt.subplots(figsize=(10, 5))

        legit = df[~df['is_flagged']]
        fraud = df[df['is_flagged']]

        ax1.scatter(range(len(legit)), legit['probability'],
                    c='green', alpha=0.5, s=10, label='Legit')
        ax1.scatter(
            [i for i, flagged in enumerate(df['is_flagged']) if flagged],
            fraud['probability'],
            c='red', alpha=0.7, s=20, label='Fraud'
        )
        ax1.axhline(y=threshold, color='red', linestyle='--',
                     label=f'Threshold ({threshold})')
        ax1.set_xlabel('Transaction Index')
        ax1.set_ylabel('Fraud Probability')
        ax1.legend()
        ax1.set_ylim(-0.05, 1.05)
        st.pyplot(fig1)
        plt.close(fig1)

    with col_chart2:
        st.subheader("📊 Risk Level Distribution")

        def get_risk(p):
            if p < 0.3:
                return 'LOW'
            if p <= 0.7:
                return 'MEDIUM'
            return 'HIGH'

        df['risk_level'] = df['probability'].apply(get_risk)
        risk_counts = df['risk_level'].value_counts()

        fig2, ax2 = plt.subplots(figsize=(8, 5))
        colors = {'LOW': '#2ecc71', 'MEDIUM': '#f39c12', 'HIGH': '#e74c3c'}
        bars = ax2.bar(
            risk_counts.index,
            risk_counts.values,
            color=[colors.get(r, 'gray') for r in risk_counts.index]
        )
        for bar, val in zip(bars, risk_counts.values):
            ax2.text(bar.get_x() + bar.get_width() / 2., bar.get_height(),
                     str(val), ha='center', va='bottom', fontweight='bold')
        ax2.set_ylabel('Count')
        ax2.set_title('Risk Distribution')
        st.pyplot(fig2)
        plt.close(fig2)

    # --- Recent Fraud Alerts Table ---
    st.subheader("🚨 Recent Fraud Alerts (Last 20)")
    frauds_df = df[df['is_flagged']].tail(20).sort_values(
        by='probability', ascending=False
    )

    if frauds_df.empty:
        st.success("✅ No frauds detected at current threshold!")
    else:
        display_cols = [c for c in ['timestamp', 'probability', 'risk_level', 'prediction']
                        if c in frauds_df.columns]
        st.dataframe(frauds_df[display_cols], use_container_width=True)

st.caption("💡 Click 'Refresh Data' in the sidebar to update. "
           "Logs are generated by the /predict API endpoint.")
